import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author silve
 */
public class CadastraAssert extends javax.swing.JFrame {

    private String login1;
    private int qtd1;
    private int question1;
    private int questao1;
    private String num_assert;
    Connection conexao = trabalho.MinhaConexao.getInstance().sqlConnection;
    JFrame father;

    /**
     * Creates new form CadastraAssert
     */
    public CadastraAssert() {
        initComponents();
        question1 = 0;
        login1 = "";
        num_assert = "0";
        questao1 = 0;
    }

    public CadastraAssert(JFrame father) {
        initComponents();
        this.father = father;
        question1 = 0;
        login1 = "";
        num_assert = "0";
        questao1 = 0;
// TODO add your handling code here:
    }

    CadastraAssert(String login, int question, String num_asser, int questao, int qtd) {
        initComponents();
        question1 = question;
        login1 = login;
        num_assert = num_asser;
        questao1 = questao;
        qtd1 = qtd;
        atualizaClientes(num_assert);
    }

    private void atualizaClientes(String nome) {
        NumAsser.setText(nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAssert = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtPesAssert = new javax.swing.JTextPane();
        btnAddAsser = new javax.swing.JButton();
        NumAsser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Insira a assertiva");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Insira a assertiva :");

        jScrollPane1.setViewportView(txtAssert);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Insira o peso da assertiva :");

        jScrollPane11.setViewportView(txtPesAssert);

        btnAddAsser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddAsser.setText("Adicionar Assertiva");
        btnAddAsser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAsserActionPerformed(evt);
            }
        });

        NumAsser.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        NumAsser.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumAsser)
                .addGap(625, 625, 625))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddAsser)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumAsser))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnAddAsser)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAsserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAsserActionPerformed
        // TODString nome = txtNome.getText();
        String ass = txtAssert.getText();
        String pes = txtPesAssert.getText();
        try {
            Statement stmt = conexao.createStatement();
            Statement stmt1 = conexao.createStatement();
            String query1;
            int cond = 0;
            if (txtAssert.getText().equals("") || txtPesAssert.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nenhum campo pode estar em branco.", "Erro ao efetuar o Cadastro!", JOptionPane.ERROR_MESSAGE);
                cond = 1;
                txtAssert.setText("");
                txtPesAssert.setText("");

            }
            if (cond == 0) {
                String query;
                query = "INSERT INTO assertivas (assertiv, peso,questao_id,question_id) VALUES ('" + ass + "','" + pes + "','" + questao1 + "','" + question1 + "')";
                stmt.executeUpdate(query);
                conexao.close();
                int i = Integer.parseInt(num_assert);
                if (i != 1) {
                    i--;
                    this.setVisible(false);
                    num_assert = Integer.toString( i );
                    CadastraAssert mc = new CadastraAssert(login1, question1, num_assert, questao1,qtd1);
                    mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                    mc.setVisible(true);
                }
                else
                {
                    this.setVisible(false);
                    CadastraResposta mc = new CadastraResposta(login1, question1, questao1,qtd1);
                    mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                    mc.setVisible(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAsserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraAssert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraAssert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraAssert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraAssert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraAssert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumAsser;
    private javax.swing.JButton btnAddAsser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTextPane txtAssert;
    private javax.swing.JTextPane txtPesAssert;
    // End of variables declaration//GEN-END:variables
}
